### ISSUE TITLE
Does it support documentation generation for offline browsing / API publishing?

### ISSUE THREAD

**Issue by ieugen** [wilkerlucio/pathom-viz#12]
Hello, 

Does the tool allow you to generate the API docs for publishing via HTTP static web server? 
This should be useful for people who don't have the tool and want to make read up on the API before deciding to use it. 

Thanks,

**Comment by wilkerlucio** [comment]
Hello, sorry for the so late answer, but let's talk about it now :)

We don't have something like that at this time, but I think we can have something like that.

I recently created a way to use Pathom Viz as an embed, and we can include the Index Explorer as a usable component, but I need to refactor some code on it to remove the usage of Fulcro to enable it to work as an embed component. This is a general refactoring I'm doing to make the individual components easier to use (by not requiring a Fulcro app around them).

I imagine we could have something that generates a simple HTML file that can setup the embed with your graph data, from the UI an export button could make that.

Do you think that would be a good solution?

I'll close this issue because I prefer to keep issues for features and code changes, let's move the discussion to the just enabled Discussions section here.

**Comment by wilkerlucio** [comment]
Continue the discussion at https://github.com/wilkerlucio/pathom-viz/discussions/27
